alias gll="git log --graph --branches --remotes --tags --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gfp="git fetch --prune"
alias gd="git diff --color-words"
alias gchanges="git log -p --reverse master..origin/master"

alias v="vagrant"
alias vst="vagrant status"
alias vu="vagrant up"
alias vd="vagrant destroy"
alias vdf="vagrant destroy -f"
alias vss="vagrant ssh"

alias vb="vagrant box"
alias vbl="vagrant box list"
alias vbu="vagrant box update"
