require 'pogopaule.options'
require 'pogopaule.keymaps'
require 'pogopaule.plugins'

require 'pogopaule.plugins.simple_setups'
require 'pogopaule.plugins.cmp'
require 'pogopaule.plugins.treesitter'
require 'pogopaule.lsp'
require 'pogopaule.plugins.comment'
require 'pogopaule.plugins.telekasten'
require 'pogopaule.plugins.gh'
